### ISSUE TITLE
Incorrect output for basic sentences

### ISSUE THREAD

**Issue by samarthsikand** [tqtrunghnvn/ActiveAndPassive#1]
Hi,
I was trying out your code but it is not working well for very basic sentences.
![prolog](https://user-images.githubusercontent.com/16184715/79902415-16426200-842f-11ea-8bf2-a760db9b7a65.JPG)

Do let me know if there is some issue with how I am using it. I was looking for rule based Active-Passive conversion tool and came across your work.

**Comment by tqtrunghnvn** [comment]
Hi,
The problem is that you did not define new words (*john, eat, food*) in the lexicon. You can define new words in **convertible.pl**.
For example, *john* will be defined as follows:
```
lex(john,pro,subject,singular).
lex(john,pro,object,singular).
```
